name: Build Windows Wheel

on:
  workflow_dispatch:

jobs:
  build_windows_wheel:
    name: Build wheel for Windows on Python 3.11
    runs-on: windows-latest

    steps:
      # 1. Скачиваем код вашего форка
      - uses: actions/checkout@v4

      # --- НОВЫЙ ШАГ: СКАЧИВАЕМ И РАСПАКОВЫВАЕМ TENSORFLOW LITE ---
      - name: Download and Unpack TensorFlow Lite
        run: |
          Invoke-WebRequest -Uri "https://storage.googleapis.com/tensorflow/versions/2.18.1/libtensorflow-cpu-windows-x86_64.zip" -OutFile tflite.zip
          Expand-Archive -Path tflite.zip -DestinationPath tflite
        shell: powershell

      # 2. Устанавливаем Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Устанавливаем Rust
      - uses: dtolnay/rust-toolchain@stable

      # 4. Собираем "колесо"
      - name: Build wheel
        # --- НОВЫЙ ШАГ: УКАЗЫВАЕМ ПУТЬ К БИБЛИОТЕКЕ TFLITE ---
        # Мы устанавливаем переменную окружения, чтобы rustc/link.exe нашли .lib файл
        env:
          RUSTFLAGS: -L ${{ github.workspace }}\tflite
        run: |
          pip install maturin
          maturin build --release --out dist --find-interpreter

      # 5. Загружаем результат
      - uses: actions/upload-artifact@v4
        with:
          name: dtln-rs-wheel-windows-py311
          path: dist
