name: Build Windows Wheel

on:
  workflow_dispatch:

jobs:
  build_windows_wheel:
    name: Build wheel for Windows on Python 3.11
    runs-on: windows-latest

    steps:
      # 1. Скачиваем код вашего форка
      - uses: actions/checkout@v4

      # 2. Скачиваем и распаковываем ПОЛНУЮ C-библиотеку TensorFlow
      - name: Download and Unpack TensorFlow C Library
        run: |
          Invoke-WebRequest -Uri "https://storage.googleapis.com/tensorflow/versions/2.18.1/libtensorflow-cpu-windows-x86_64.zip" -OutFile tf_c.zip
          Expand-Archive -Path tf_c.zip -DestinationPath tf_c
        shell: powershell

      # 3. Устанавливаем Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 4. Устанавливаем Rust
      - uses: dtolnay/rust-toolchain@stable

      # 5. Собираем "колесо" с правильным путем к библиотеке
      - name: Build wheel
        env:
          # Указываем компоновщику точный путь к папке 'lib' внутри скачанного архива
          RUSTFLAGS: -L ${{ github.workspace }}\tf_c\lib
        run: |
          pip install maturin
          maturin build --release --out dist --find-interpreter

      # 6. Загружаем результат
      - uses: actions/upload-artifact@v4
        with:
          name: dtln-rs-wheel-windows-py311
          path: dist
