name: Build Windows Wheel

on:
  workflow_dispatch:

jobs:
  build_windows_wheel:
    name: Build wheel for Windows on Python 3.11
    runs-on: windows-latest

    steps:
      # 1. Скачиваем код вашего форка
      - uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Устанавливаем Rust
      - uses: dtolnay/rust-toolchain@stable

      # 4. Клонируем репозиторий TensorFlow
      - name: Clone TensorFlow repository
        run: git clone https://github.com/tensorflow/tensorflow.git

      # 5. Устанавливаем CMake
      - name: Install CMake
        uses: lukka/get-cmake@v3
        with:
          cmake-version: "3.26.0"

      # 6. Собираем TensorFlow Lite C++
      - name: Build TensorFlow Lite C++
        shell: pwsh
        run: |
          cd tensorflow
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DTENSORFLOW_LITE_BUILD=ON ..
          cmake --build . --config Release

      # 7. Копируем библиотеку TensorFlow Lite C++
      - name: Copy TensorFlow Lite C++ library
        shell: pwsh
        run: |
          Copy-Item -Path "tensorflow/build/Release/tensorflowlite.dll" -Destination "tflite_lib/tensorflowlite_c.dll"
          Copy-Item -Path "tensorflow/build/Release/tensorflowlite.lib" -Destination "tflite_lib/tensorflowlite_c.lib"

      # 8. Собираем "колесо"
      - name: Build wheel
        shell: bash
        run: |
          pip install maturin
          maturin build --release --out dist --find-interpreter

      # 9. Загружаем результат
      - uses: actions/upload-artifact@v4
        with:
          name: dtln-rs-wheel-windows-py311
          path: dist
